openapi: 3.0.0
info:
  title: Астрон личный кабинет API
  description: API для работы личного кабинета Астрон
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Локальный сервер
  - url: https://astronbuildings.com
    description: Боевой сервер
paths:
  /api/login:
    post:
      summary: Аутентификация
      operationId: login
      tags:
        - Пользователь
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  example: dev@mail.ru
                password:
                  type: string
                  example: password
                remember:
                  type: boolean
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        "400":
          description: Ошибка ввода данных
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Неверный логин или пароль
        "403":
          description: Пользователь забанен
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Ваш аккаунт заблокирован
  /api/refreshToken:
    get:
      summary: Обновление токенов
      operationId: refreshToken
      tags:
        - Пользователь
      parameters:
        - name: refreshToken
          in: cookie
          description: Refresh Token с клиента
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        "401":
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Refresh token is invalid
  /api/restorePassword:
    post:
      summary: Восстановление пароля
      operationId: restoreUserPassword
      tags:
        - Пользователь
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
      responses:
        "200":
          description: Пароль успешно изменен
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Пароль успешно изменен
        "400":
          description: Ошибка
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Пароли не совпадают
  /api/getSession:
    get:
      summary: Получение сессии
      operationId: getSession
      tags:
        - Пользователь
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
        "401":
          description: Ошибка авторизации
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Пользователь не авторизован
  /api/news:
    get:
      summary: Получить список новостей
      operationId: listNews
      tags:
        - Новости
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/News"
      security:
        - bearerAuth: []
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "1"
        surname:
          type: string
          example: Королев
        name:
          type: string
          example: Данил
        patronymic:
          type: string
          example: Николаевич
        email:
          type: string
          example: dev@mail.ru
        password:
          type: string
          example: 123
        tokenVersion:
          type: integer
        isBanned:
          type: boolean
    Session:
      type: object
      properties:
        email:
          type: string
          example: dev@mail.ru
        surname:
          type: string
          example: Королев
        name:
          type: string
          example: Данил
        patronymic:
          type: string
          example: Николаевич
    News:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: Ключевая ставка достигла 30%
        description:
          type: string
          example: Деняк нет, но вы держитесь
        createdAt:
          type: string
          example: "2024-12-30"
          format: date
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
