openapi: 3.0.0
info:
  title: Астрон личный кабинет API
  description: API для работы личного кабинета Астрон
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Локальный сервер
  - url: https://astronbuildings.com
    description: Боевой сервер
paths:
  "/users":
    get:
      summary: Получить список пользователей
      operationId: listUsers
      tags:
        - users
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  "/news":
    get:
      summary: Получить список новостей
      operationId: listNews
      tags:
        - news
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/News"
    post:
      summary: Создать новую новость
      operationId: createPost
      tags:
        - news
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/News"
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/News"
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          example: "1"
        name:
          type: string
          example: John Doe
        email:
          type: string
          example: johndoe@example.com
    News:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: Ключевая ставка достигла 30%
        description:
          type: string
          example: Деняк нет, но вы держитесь
        createdAt:
          type: string
          example: "2024-12-30"
          format: date
